# Generated by Django 2.0.6 on 2018-10-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='raza',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
