# Generated by Django 2.0.6 on 2018-10-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_adoptarrescatado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptarrescatado',
            name='celular',
            field=models.IntegerField(),
        ),
    ]
